apiVersion: apps/v1
kind: Deployment
metadata:
  name: ck-website
  labels:
    app: ck-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ck-website
  template:
    metadata:
      labels:
        app: ck-website
    spec:
      imagePullSecrets:
        - name: ckn-ghcr-secret
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
      containers:
      - name: ck-website
        image: ghcr.io/sabareesh-ckt/ck-website/ck-website:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: DB_HOST
          value: "ck-postgres.codekarma"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "cknexus"
        - name: DB_PASSWORD
          value: "cknexus"
        - name: DB_NAME
          value: "ckservicedb"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ck-website
  labels:
    app: ck-website
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: ck-website